// Parsed WBS Data with suggestion checklists
const WBS_DATA = [
  {
    "Task Name": "Appreciation Day: Awards & 2026 Reveal",
    "Progress": "Completed on 21 January 2026",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "1-Jan-2026",
    "Month Start": "January",
    "Deadline": "28-Jan-2026",
    "Duration (Days)": "27",
    "Day Left Start(Days)": "-182",
    "Day Left (Days)": "-155",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Malaysian Chinese Education Week Hefei",
    "Progress": "Completed on 19 January 2026",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "14-Jan-2026",
    "Month Start": "January",
    "Deadline": "20-Jan-2026",
    "Duration (Days)": "6",
    "Day Left Start(Days)": "-169",
    "Day Left (Days)": "-163",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "AI \"Aiza\" Soft Launch: Knowledge Base Setup",
    "Progress": "In Progress together with Faculty Website RSCI",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "21-Jan-2026",
    "Month Start": "January",
    "Deadline": "24-Apr-2026",
    "Duration (Days)": "93",
    "Day Left Start(Days)": "-162",
    "Day Left (Days)": "-69",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Installation of CostX",
    "Progress": "Installed by ICT",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "2-Feb-2026",
    "Month Start": "February",
    "Deadline": "9-Feb-2026",
    "Duration (Days)": "7",
    "Day Left Start(Days)": "-150",
    "Day Left (Days)": "-143",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Staff for Teaching Competition Prep",
    "Progress": "FABE will be the first faculty to hold it, TsIdris, Basir,TsMazlina and DrAdil will represent FABE for the first round.",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 9: Talent Management Governance and Organisational Excellence",
    "RASCI": "HOP/s",
    "Category": "Competition",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "6-Feb-2026",
    "Month Start": "February",
    "Deadline": "2-Mar-2026",
    "Duration (Days)": "24",
    "Day Left Start(Days)": "-146",
    "Day Left (Days)": "-122",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Ownership Handover: Sign RASCI/ToRs",
    "Progress": "Plan for Faculty to be shared in Meeting",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC",
    "Strategic Thrust": "Strategy Thrust 6: Financial Sustainability and Resource Optimisation",
    "RASCI": "Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "11-Feb-2026",
    "Month Start": "February",
    "Deadline": "3-Mar-2026",
    "Duration (Days)": "20",
    "Day Left Start(Days)": "-141",
    "Day Left (Days)": "-121",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Student Voice Survey: Baseline Satisfaction",
    "Progress": "To be developed by IT team",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "HOP/s, Cluster Leader, Academic Executive",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "11-Feb-2026",
    "Month Start": "February",
    "Deadline": "3-Mar-2026",
    "Duration (Days)": "20",
    "Day Left Start(Days)": "-141",
    "Day Left (Days)": "-121",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Policy Pitch: Budget for 3D/Staff Ratios",
    "Progress": "Plan for Faculty to be shared in Meeting, next meeting is on April 2",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "11-Feb-2026",
    "Month Start": "February",
    "Deadline": "10-Apr-2026",
    "Duration (Days)": "58",
    "Day Left Start(Days)": "-141",
    "Day Left (Days)": "-83",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Curriculum Patch: BIM/AI/Sustainability",
    "Progress": "To be identified by HOP",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate, UAC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE, HOP/s, Cluster Leader, Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "11-Feb-2026",
    "Month Start": "February",
    "Deadline": "31-Mar-2026",
    "Duration (Days)": "48",
    "Day Left Start(Days)": "-141",
    "Day Left (Days)": "-93",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Website Launch",
    "Progress": "Need to identify Author, Combined in Website as FABE Activity Report",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, HOP/s, Cluster Leader, Studio Master",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "11-Feb-2026",
    "Month Start": "February",
    "Deadline": "30-Apr-2026",
    "Duration (Days)": "78",
    "Day Left Start(Days)": "-141",
    "Day Left (Days)": "-63",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "ARCA: Souq ARCA 26",
    "Progress": "Prepared by ARCA Students",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Studio Master, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "13-Feb-2026",
    "Month Start": "February",
    "Deadline": "13-Feb-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-139",
    "Day Left (Days)": "-139",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Training on Gems to EMC",
    "Progress": "Delivered",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "19-Feb-2026",
    "Month Start": "February",
    "Deadline": "11-Mar-2026",
    "Duration (Days)": "20",
    "Day Left Start(Days)": "-133",
    "Day Left (Days)": "-113",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Faculty Budget 2026",
    "Progress": "Submitted to Prof Huam, need to identify the champions fro major program",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 6: Financial Sustainability and Resource Optimisation",
    "RASCI": "Dean FABE, Academic Executive",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "20-Feb-2026",
    "Month Start": "February",
    "Deadline": "15-Mar-2026",
    "Duration (Days)": "23",
    "Day Left Start(Days)": "-132",
    "Day Left (Days)": "-109",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "KLUST Strategic Foundation & Strategic Direction 2026: Phase 1",
    "Progress": "Submitted to Prof Huam, need to identify the champions fro major program",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 9: Talent Management Governance and Organisational Excellence",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "23-Feb-2026",
    "Month Start": "February",
    "Deadline": "13-Mar-2026",
    "Duration (Days)": "18",
    "Day Left Start(Days)": "-129",
    "Day Left (Days)": "-111",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Dual Degree Program:Smart Construction Phase 1",
    "Progress": "Shafiq is looking mapping the syllabus",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 5: Building A Global Connected University",
    "RASCI": "HOP/s, Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "24-Feb-2026",
    "Month Start": "February",
    "Deadline": "18-Mar-2026",
    "Duration (Days)": "22",
    "Day Left Start(Days)": "-128",
    "Day Left (Days)": "-106",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Check the Entry Requirements for All Program",
    "Progress": "Done",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Studio Master",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "27-Feb-2026",
    "Month Start": "February",
    "Deadline": "2-Mar-2026",
    "Duration (Days)": "3",
    "Day Left Start(Days)": "-125",
    "Day Left (Days)": "-122",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Symposium Lockdown: Partners & Tech",
    "Progress": "Initiated to be integrated with UGCS. To be discussed in April meeting",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "HOP/s",
    "Category": "Research & Development",
    "Status": "In Progress",
    "Progress %": "30.00%",
    "Start Date": "2-Mar-2026",
    "Month Start": "March",
    "Deadline": "31-Jul-2026",
    "Duration (Days)": "151",
    "Day Left Start(Days)": "-122",
    "Day Left (Days)": "29",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Re-engage with the Undergraduate Committee/Seminar (UGCS) coordinator to align integration rules",
      "Draft a standard sponsor/partner MoU template detailing sponsorship tiers",
      "Establish a tech stack checklist (online ticketing, webinar platform, stream setup)",
      "Pitch the integrated proposal and budget structure to EMC for approval",
      "Send out initial invitation letters and 'Save the Date' notices to prospective speakers"
    ]
  },
  {
    "Task Name": "Teaching Competition March",
    "Progress": "Done, won by Mohd Basir Landscape Arch",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Competition",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "3-Mar-2026",
    "Month Start": "March",
    "Deadline": "3-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-121",
    "Day Left (Days)": "-121",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Teaching Competition May",
    "Progress": "Done, won by Zairila Juriah Arch",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "FABE Lecturers, HOP/s",
    "Category": "Competition",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "18-May-2026",
    "Month Start": "May",
    "Deadline": "18-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-45",
    "Day Left (Days)": "-45",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Final Crit 3A",
    "Progress": "Final Crit Week 1",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "9-Mar-2026",
    "Month Start": "March",
    "Deadline": "9-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-115",
    "Day Left (Days)": "-115",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Universal Design for Learning (UDL) Policy",
    "Progress": "Presented to EMC but proposed to have Task Force at University Level",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, Studio Master, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "10-Mar-2026",
    "Month Start": "March",
    "Deadline": "10-Apr-2026",
    "Duration (Days)": "31",
    "Day Left Start(Days)": "-114",
    "Day Left (Days)": "-83",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Final Crit 1B",
    "Progress": "Final Crit Week 1",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "10-Mar-2026",
    "Month Start": "March",
    "Deadline": "10-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-114",
    "Day Left (Days)": "-114",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Final Crit 2B",
    "Progress": "Final Crit Week 1",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "80.00%",
    "Start Date": "12-Mar-2026",
    "Month Start": "March",
    "Deadline": "12-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-112",
    "Day Left (Days)": "-112",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Iftar ArchiCLUB",
    "Progress": "Iftar session",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "HOP/s, Dean FABE",
    "Category": "Community & Industry Engagement",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "12-Mar-2026",
    "Month Start": "March",
    "Deadline": "12-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-112",
    "Day Left (Days)": "-112",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Final Crit 3B",
    "Progress": "Final Crit Week 1",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "13-Mar-2026",
    "Month Start": "March",
    "Deadline": "13-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-111",
    "Day Left (Days)": "-111",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "FABE Staff Training Budget and Planning",
    "Progress": "Item to be discussed in Meeting April",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 9: Talent Management Governance and Organisational Excellence",
    "RASCI": "Dean FABE, Academic Executive",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "16-Mar-2026",
    "Month Start": "March",
    "Deadline": "10-Apr-2026",
    "Duration (Days)": "25",
    "Day Left Start(Days)": "-108",
    "Day Left (Days)": "-83",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "BSAR Portfolio Day Semester Nov 2025",
    "Progress": "Call for EEs",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "HOP/s, Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "16-Mar-2026",
    "Month Start": "March",
    "Deadline": "16-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-108",
    "Day Left (Days)": "-108",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Final Presentation BQS",
    "Progress": "Call for EEs",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "HOP/s, Studio Master",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "16-Mar-2026",
    "Month Start": "March",
    "Deadline": "16-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-108",
    "Day Left (Days)": "-108",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Dual Degree Program:Smart Construction Phase 2",
    "Progress": "Fixing the Gap, next meeting on 7 April 2026",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 5: Building A Global Connected University",
    "RASCI": "HOP/s, Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "10.00%",
    "Start Date": "18-Mar-2026",
    "Month Start": "March",
    "Deadline": "15-Apr-2026",
    "Duration (Days)": "28",
    "Day Left Start(Days)": "-106",
    "Day Left (Days)": "-78",
    "Milestone": "",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "BTCM KLUST Hefei 2+2 (Phase 2)",
    "Progress": "Phase 2 in Progress: waiting for Hefei feedback and MOU",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "KLUST",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "27-Mar-2026",
    "Month Start": "March",
    "Deadline": "15-May-2026",
    "Duration (Days)": "49",
    "Day Left Start(Days)": "-97",
    "Day Left (Days)": "-48",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "BTCM KLUST Hefei 2+2 (Phase 1)",
    "Progress": "Completed Phase 1 (2nd Meeting with Hefei)",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "HOP/s, Dean FABE",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "30-Mar-2026",
    "Month Start": "March",
    "Deadline": "27-Mar-2026",
    "Duration (Days)": "-3",
    "Day Left Start(Days)": "-94",
    "Day Left (Days)": "-97",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Examination Week Nov 2025",
    "Progress": "Ongoing",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "KLUST",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "50.00%",
    "Start Date": "30-Mar-2026",
    "Month Start": "March",
    "Deadline": "10-Apr-2026",
    "Duration (Days)": "11",
    "Day Left Start(Days)": "-94",
    "Day Left (Days)": "-83",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "DAR Portfolio Semester Nov 2025",
    "Progress": "Call for EEs",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "Studio Master, HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "30-Mar-2026",
    "Month Start": "March",
    "Deadline": "30-Mar-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-94",
    "Day Left (Days)": "-94",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "FABE in Action Initiative 1: Mobile STEM",
    "Progress": "Pitch for Budget",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 5: Building A Global Connected University",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "20.00%",
    "Start Date": "1-Apr-2026",
    "Month Start": "April",
    "Deadline": "30-Apr-2026",
    "Duration (Days)": "29",
    "Day Left Start(Days)": "-92",
    "Day Left (Days)": "-63",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Refine the budget request for Mobile STEM equipment and submit to EMC",
      "Draft lesson plans and hands-on activities suitable for school kids",
      "Reach out to local primary/secondary schools to book visit slots"
    ]
  },
  {
    "Task Name": "FABE in Action Initiative 2: CSR in Studio",
    "Progress": "Pitch for Budget",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "15.00%",
    "Start Date": "1-Apr-2026",
    "Month Start": "April",
    "Deadline": "30-Apr-2026",
    "Duration (Days)": "29",
    "Day Left Start(Days)": "-92",
    "Day Left (Days)": "-63",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review current studio project briefs and identify community partners",
      "Present CSR budget pitch to EMC highlighting student ESG compliance",
      "Establish contact with beneficiary community for site analysis"
    ]
  },
  {
    "Task Name": "FABE Showcase Display",
    "Progress": "Pitch for Budget and Place",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "10.00%",
    "Start Date": "1-Apr-2026",
    "Month Start": "April",
    "Deadline": "30-Apr-2026",
    "Duration (Days)": "29",
    "Day Left Start(Days)": "-92",
    "Day Left (Days)": "-63",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Determine space size for showcase display on campus",
      "Draft material cost budget and design layout options for presentation",
      "Form a student setup committee from ARCA to assist with physical builds"
    ]
  },
  {
    "Task Name": "DLAR BLAR Portfolio Semester Nov 2025",
    "Progress": "Call for EEs",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "Studio Master, HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "1-Apr-2026",
    "Month Start": "April",
    "Deadline": "1-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-92",
    "Day Left (Days)": "-92",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Benchmark Visit by Kolej Komuniti Tanjung Karang",
    "Progress": "Sucessfully Done",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "1-Apr-2026",
    "Month Start": "April",
    "Deadline": "1-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-92",
    "Day Left (Days)": "-92",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Faculty Meeting April 2026",
    "Progress": "Done",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "2-Apr-2026",
    "Month Start": "April",
    "Deadline": "2-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-91",
    "Day Left (Days)": "-91",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Marketing:  Online Trial Class ; Introduction to Architecture\nSMK Chio Min, Kedah.👥 350 students form 4 & 350 students form 5.",
    "Progress": "Completed by Azrin and Zairila",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "11-Apr-2026",
    "Month Start": "April",
    "Deadline": "11-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-82",
    "Day Left (Days)": "-82",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Training on MQF 2.0 (VBE and SDE) Phase 1",
    "Progress": "Completed 2 days/3 days",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "13-Apr-2026",
    "Month Start": "April",
    "Deadline": "16-Apr-2026",
    "Duration (Days)": "3",
    "Day Left Start(Days)": "-80",
    "Day Left (Days)": "-77",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Faculty Board of Examination",
    "Progress": "Done",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "13-Apr-2026",
    "Month Start": "April",
    "Deadline": "13-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-80",
    "Day Left (Days)": "-80",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Task Force for UDL (iTnL)",
    "Progress": "Draft Completed",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, Senate",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, KLUST",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "50.00%",
    "Start Date": "16-Apr-2026",
    "Month Start": "April",
    "Deadline": "31-May-2026",
    "Duration (Days)": "45",
    "Day Left Start(Days)": "-77",
    "Day Left (Days)": "-32",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Retrieve draft policy documents and compile feedback from the initial EMC pitch",
      "Schedule the first Task Force alignment meeting with key representatives from KLUST ITnL",
      "Refine UDL policy guidelines to match the university-level academic frameworks"
    ]
  },
  {
    "Task Name": "Leadership to Market Impact Training",
    "Progress": "Completed 2.5 days",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record, EMC",
    "Strategic Thrust": "Strategy Thrust 6: Financial Sustainability and Resource Optimisation",
    "RASCI": "KLUST",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "20-Apr-2026",
    "Month Start": "April",
    "Deadline": "22-Apr-2026",
    "Duration (Days)": "2",
    "Day Left Start(Days)": "-73",
    "Day Left (Days)": "-71",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "CIDB BIM Basic Training",
    "Progress": "HRDF Claimable for 15 staffs",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE, Cluster Leader, FABE Lecturers",
    "Category": "Academics & Teaching",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "21-Apr-2026",
    "Month Start": "April",
    "Deadline": "21-Apr-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-72",
    "Day Left (Days)": "-72",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Training on MQF 2.0 (VBE and SDE) Phase 2",
    "Progress": "Done by Zairila and HOPs involved are ganted to become Internel Auditor for OBE",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, Senate",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "5-May-2026",
    "Month Start": "May",
    "Deadline": "5-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-58",
    "Day Left (Days)": "-58",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Measured Drawing Visit IPOH (Local Council Kick Off",
    "Progress": "Measured Drawing in Ipoh and visit to MBI",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "FABE Lecturers",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "6-May-2026",
    "Month Start": "May",
    "Deadline": "9-May-2026",
    "Duration (Days)": "3",
    "Day Left Start(Days)": "-57",
    "Day Left (Days)": "-54",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Briefing on FABE: Carrer Clinic 2026",
    "Progress": "Visit and Clinic for SMA Auliyah Jakarta",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC",
    "Strategic Thrust": "Strategy Thrust 5: Building A Global Connected University",
    "RASCI": "Dean FABE, HOP/s, FABE Lecturers",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "6-May-2026",
    "Month Start": "May",
    "Deadline": "6-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-57",
    "Day Left (Days)": "-57",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Marketing: SMK Proton City Tanjung Malim",
    "Progress": "Done by AP Md Pilus and Dr Adil",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "UAC, Record",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "FABE Lecturers",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "7-May-2026",
    "Month Start": "May",
    "Deadline": "7-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-56",
    "Day Left (Days)": "-56",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Lecture on FORMA at UPM: From Initation to Implimentation",
    "Progress": "Lecture to Master of Architecture Student",
    "Major Issue/Incident": "Not a direct marketing to KLUST",
    "Action Taken": "Possible for Micro Credential",
    "Report to": "UAC, Record",
    "Strategic Thrust": "Strategy Thrust 5: Building A Global Connected University",
    "RASCI": "Dean FABE",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "8-May-2026",
    "Month Start": "May",
    "Deadline": "8-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-55",
    "Day Left (Days)": "-55",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Facilities and Plan for FABE at Block 11 (Phase 1)-Planning",
    "Progress": "Started for Floor Plan and Moving of Gallery",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, Academic Executive, Studio Master",
    "Category": "Administrative & Faculty Development",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "12-May-2026",
    "Month Start": "May",
    "Deadline": "1-Jun-2026",
    "Duration (Days)": "20",
    "Day Left Start(Days)": "-51",
    "Day Left (Days)": "-31",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Facilities and Plan for FABE at Block 11 (Phase 2) - Mobilisation and Design",
    "Progress": "Clear the gallery started and identified the model to be displayed at lvl 9",
    "Major Issue/Incident": "Some model need to be upgraded and size are varies",
    "Action Taken": "Standard Model Size and Drawing size in future gallery",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, FABE Lecturers, Academic Executive",
    "Category": "Administrative & Faculty Development",
    "Status": "Milestone",
    "Progress %": "100.00%",
    "Start Date": "25-May-2026",
    "Month Start": "May",
    "Deadline": "12-Jun-2026",
    "Duration (Days)": "18",
    "Day Left Start(Days)": "-38",
    "Day Left (Days)": "-20",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Facilities and Plan for FABE at Block 11 (Phase 3) - New Gallery Design and Lvl 4 Upgrade",
    "Progress": "Design of New Gallery and Upgrade of Lvl 4 Corridor",
    "Major Issue/Incident": "Need 2 Smart TVs",
    "Action Taken": "Preparing Memo from Chairman and Discussion with Mr.Liu",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "Milestone",
    "Progress %": "20.00%",
    "Start Date": "16-May-2026",
    "Month Start": "May",
    "Deadline": "20-Jun-2026",
    "Duration (Days)": "35",
    "Day Left Start(Days)": "-47",
    "Day Left (Days)": "-12",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/fabe+gallery/FMfcgzQgMCWFLCgsLfHTFmbdWCCLqzld",
    "suggestions": [
      "Finalize gallery layout blueprints and Level 4 corridor refurbishment drawings",
      "Draft the memo requesting budget for 2 Smart TVs from the Chairman",
      "Set up a coordination meeting with Mr. Liu to discuss facilities support and timeline"
    ]
  },
  {
    "Task Name": "Faculty Meeting May 2026",
    "Progress": "Done",
    "Major Issue/Incident": "VBE and SDE implementation",
    "Action Taken": "Call for CDPs",
    "Report to": "Record, UAC",
    "Strategic Thrust": "ROUTINE",
    "RASCI": "Dean FABE, HOP/s, FABE Lecturers",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "15-May-2026",
    "Month Start": "May",
    "Deadline": "15-May-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-48",
    "Day Left (Days)": "-48",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Renew SketchUp Licence",
    "Progress": "EMC Paper: proposed to reduce to 20 pax",
    "Major Issue/Incident": "EMC Postponed",
    "Action Taken": "By Memorandum",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "Dean FABE",
    "Category": "Research & Development",
    "Status": "In Progress",
    "Progress %": "70.00%",
    "Start Date": "20-May-2026",
    "Month Start": "May",
    "Deadline": "26-Jun-2026",
    "Duration (Days)": "37",
    "Day Left Start(Days)": "-43",
    "Day Left (Days)": "-6",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/sketchup+pro+renewal/KtbxLxGPlKtCmMGWVdCsktSCPHLrRJmBLq",
    "suggestions": [
      "Revise the EMC memorandum proposing a reduction in license seats to 20 pax (highlighting cost benefits)",
      "Request updated vendor quotation matching the reduced license count",
      "Submit the memo for fast-track approval to avoid design studio software lockouts",
      "Initiate purchase order creation once EMC approves the request"
    ]
  },
  {
    "Task Name": "Mid-Year Pulse: Facilities \"MQA Visit\"",
    "Progress": "Met FM and most items are in place",
    "Major Issue/Incident": "No Gallery",
    "Action Taken": "Setup Exhibition at IDEA room just for DLAR",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, Academic Executive",
    "Category": "Administrative & Faculty Development",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "15-May-2026",
    "Month Start": "May",
    "Deadline": "5-Jun-2026",
    "Duration (Days)": "21",
    "Day Left Start(Days)": "-48",
    "Day Left (Days)": "-27",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "ASEAN Symposium: Major Event & Expo ICREATE 2027 (Concept and Committee)",
    "Progress": "Started",
    "Major Issue/Incident": "Look at collobration with USGC and other faculties",
    "Action Taken": "Discussion in progress",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "Dean FABE, KLUST",
    "Category": "Community & Industry Engagement",
    "Status": "Milestone",
    "Progress %": "20.00%",
    "Start Date": "15-May-2026",
    "Month Start": "May",
    "Deadline": "30-Jun-2026",
    "Duration (Days)": "46",
    "Day Left Start(Days)": "-48",
    "Day Left (Days)": "-2",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Draft the concept note for ICREATE 2027 highlighting international themes",
      "Submit proposal to UAC/EMC for committee framework and initial funding validation",
      "Identify potential collaborating departments (e.g. engineering, business) across USGC"
    ]
  },
  {
    "Task Name": "BIM Modelling Training",
    "Progress": "Basic BIM Modelling using Revit",
    "Major Issue/Incident": "Have to be posponed",
    "Action Taken": "Holiday and Tight Calendar",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE, FABE Lecturers",
    "Category": "Academics & Teaching",
    "Status": "In Progress",
    "Progress %": "10.00%",
    "Start Date": "4-Jun-2026",
    "Month Start": "June",
    "Deadline": "25-Jun-2026",
    "Duration (Days)": "21",
    "Day Left Start(Days)": "-28",
    "Day Left (Days)": "-7",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Scan calendar for open training slots during study break weeks in July/August",
      "Contact BIM trainer to reschedule dates and update training fees",
      "Create a signup roster for lecturers and confirm commitment of at least 15 participants"
    ]
  },
  {
    "Task Name": "Budget Pitch for Student Architectural Workshop 2026: Competition",
    "Progress": "ARCA applied thru STAM",
    "Major Issue/Incident": "Student claims that budget of RM3000 is not enough",
    "Action Taken": "Advise ARCA to thinking of fund rising in other method",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Students",
    "Category": "Competition",
    "Status": "In Progress",
    "Progress %": "60.00%",
    "Start Date": "11-May-2026",
    "Month Start": "May",
    "Deadline": "5-Jun-2026",
    "Duration (Days)": "25",
    "Day Left Start(Days)": "-52",
    "Day Left (Days)": "-27",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/workshop/FMfcgzQgLrzgQZxqXhSXvWKNXcVLsbKp",
    "suggestions": [
      "Review ARCA's budget breakdown and identify items that can be optimized",
      "Guide ARCA on starting a student-led fundraising campaign (merchandise, bake sales, design services)",
      "Schedule a meeting with STAM to check for additional central student funds"
    ]
  },
  {
    "Task Name": "Preparation for PASWEE 26",
    "Progress": "Preparation to enter Competition: Students Identified",
    "Major Issue/Incident": "Most ARCA leaders is doing Industrial Training, not in campus",
    "Action Taken": "Request lecturers to consider participating",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "Students, FABE Lecturers",
    "Category": "Competition",
    "Status": "In Progress",
    "Progress %": "40.00%",
    "Start Date": "1-Jun-2026",
    "Month Start": "June",
    "Deadline": "30-Jun-2026",
    "Duration (Days)": "29",
    "Day Left Start(Days)": "-31",
    "Day Left (Days)": "-2",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/PAASWE/FMfcgzQgLsFHMmbzSBxQwqvpRDcNjlbX",
    "suggestions": [
      "Identify prospective student participants from junior/senior years",
      "Assign advising lecturers to mentor the students for the PASWEE competition",
      "Review competition guidelines and design briefs to outline resource requirements"
    ]
  },
  {
    "Task Name": "Mula Semula Architecture Student Workshop (Phase 1)",
    "Progress": "Preparation for the Workshop",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Students, FABE Lecturers",
    "Category": "Competition",
    "Status": "Not Start",
    "Progress %": "",
    "Start Date": "27-Jul-2026",
    "Month Start": "July",
    "Deadline": "10-Oct-2026",
    "Duration (Days)": "75",
    "Day Left Start(Days)": "25",
    "Day Left (Days)": "100",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/workshop/FMfcgzQgLrzgQZxqXhSXvWKNXcVLsbKp",
    "suggestions": [
      "Convene a planning meeting with ARCA student leaders and advising lecturers",
      "Finalize workshop schedule, booking venues, and logistics safety plans",
      "Form a fundraising sub-committee targeting industry sponsors and alumni to supplement the RM3000 budget",
      "Establish online registration channels and publish marketing collateral",
      "Submit the finalized workshop plan and sponsor details to EMC for validation"
    ]
  },
  {
    "Task Name": "Proposal for My Lestari Corner Structure",
    "Progress": "Proposal in progress, working on budget",
    "Major Issue/Incident": "Raised up in Marketing Meeting on placing KLUST plaqes in school",
    "Action Taken": "Forward the proposal to Marketing as a sustainable Program, benefit all on sustainability strategic thrust",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "FABE Lecturers, Students",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "50.00%",
    "Start Date": "19-May-2026",
    "Month Start": "May",
    "Deadline": "12-Jun-2026",
    "Duration (Days)": "24",
    "Day Left Start(Days)": "-44",
    "Day Left (Days)": "-20",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/jaysern%40klust.edu.my/FMfcgzQbfxhklnXVFKpwswLnRdXrbhhW",
    "suggestions": [
      "Finalize the Lestari Corner design draft and material cost sheet",
      "Present proposal to Marketing as a branding and sustainability partnership program",
      "Draft a placement agreement with target schools for mounting KLUST plaques"
    ]
  },
  {
    "Task Name": "Workshop Technician replacement",
    "Progress": "In process of transferring Mr Emirul from Asset and Facilities",
    "Major Issue/Incident": "Entering Competition soon",
    "Action Taken": "Requested to HR",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 9: Talent Management Governance and Organisational Excellence",
    "RASCI": "Dean FABE, HOP/s, Academic Executive",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "50.00%",
    "Start Date": "16-May-2026",
    "Month Start": "May",
    "Deadline": "20-Jul-2026",
    "Duration (Days)": "65",
    "Day Left Start(Days)": "-47",
    "Day Left (Days)": "18",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/memo+new/QgrcJHrnzJZKlrbkJgBXwQnjbmwmsHLqfKL",
    "suggestions": [
      "Follow up with HR on the status of transferring Mr. Emirul from Assets and Facilities",
      "Draft a transition schedule and list of workshop machines for training",
      "Implement interim safety guidelines and workspace rules during the transition",
      "Confirm the official start date and issue standard access keys"
    ]
  },
  {
    "Task Name": "Appointment of New FT Architecture Lecturer",
    "Progress": "Interviewied",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 9: Talent Management Governance and Organisational Excellence",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "70.00%",
    "Start Date": "1-Jun-2026",
    "Month Start": "June",
    "Deadline": "1-Jul-2026",
    "Duration (Days)": "30",
    "Day Left Start(Days)": "-31",
    "Day Left (Days)": "-1",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/memo+new+lecturer/KtbxLvHHkVqFwVVxkfRlsFqWXxvPswRfNq",
    "suggestions": [
      "Compile interview assessment sheets and compile the recommendation memo for the dean's signature",
      "Submit hiring proposal and salary package approval request to HR & EMC",
      "Develop the onboarding program (office space, software licenses, syllabus materials)",
      "Schedule the lecturer onboarding briefing once the contract is signed by HR"
    ]
  },
  {
    "Task Name": "Heritage Project: Identify new items for Gallery",
    "Progress": "Lookup for final presentation items",
    "Major Issue/Incident": "Non Standard Model Size",
    "Action Taken": "Notify the Subject Lecturer",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Dean FABE, Cluster Leader",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "70.00%",
    "Start Date": "8-Jun-2026",
    "Month Start": "June",
    "Deadline": "3-Jul-2026",
    "Duration (Days)": "25",
    "Day Left Start(Days)": "-24",
    "Day Left (Days)": "1",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Collect model photos and dimensions from subject lecturers",
      "Measure gallery space and identify empty display slots matching selected models",
      "Create a model submission guidelines document for future design studios",
      "Instruct the display setup team to clean up and place the new heritage items"
    ]
  },
  {
    "Task Name": "Study Tour Guiling University of Electronic Technology",
    "Progress": "Proposing the activities",
    "Major Issue/Incident": "",
    "Action Taken": "Proposal sent to PSPO",
    "Report to": "EMC, UAC",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "Dean FABE, FABE Lecturers",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "20.00%",
    "Start Date": "1-Jun-2026",
    "Month Start": "June",
    "Deadline": "7-Sep-2026",
    "Duration (Days)": "98",
    "Day Left Start(Days)": "-31",
    "Day Left (Days)": "67",
    "Milestone": "Yes",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/study+visit/FMfcgzQgMChSkbFHwxhjQpSzrZCgwFdJ",
    "suggestions": [
      "Check approval status of the activity proposal with the PSPO international office",
      "Detail the day-by-day tour itinerary, prioritizing university exchanges and site visits",
      "Obtain quotations for group flights and accommodations to lock the budget",
      "Send out a call for expression of interest to FABE students to gauge participation size"
    ]
  },
  {
    "Task Name": "BTCM KLUST Hefei 2+2 (Phase 3)",
    "Progress": "Proposing the Academic Landscape",
    "Major Issue/Incident": "Hefei side seems not understanding the Academic Landscape that works for KLUST",
    "Action Taken": "Developing a proposed Academic Landscape that suit the Malaysian Requirements",
    "Report to": "EMC",
    "Strategic Thrust": "Strategy Thrust 4: Internationalisation and Global Partnership",
    "RASCI": "Dean FABE, HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "50.00%",
    "Start Date": "8-Jun-2026",
    "Month Start": "June",
    "Deadline": "17-Jun-2026",
    "Duration (Days)": "9",
    "Day Left Start(Days)": "-24",
    "Day Left (Days)": "-15",
    "Milestone": "Yes",
    "Link to document": "KLUST 2+2 Workplan Smart Construction - Google Sheets",
    "suggestions": [
      "Create a flowchart comparing MQA requirements with Chinese curriculum models to simplify explanation",
      "Prepare a bilingual slide deck (English & Chinese) outlining academic credit transfer gaps",
      "Schedule a virtual workshop with the Hefei academic coordinator to review curriculum matching",
      "Draft a formal academic landscape proposal and seek preliminary Senate approval"
    ]
  },
  {
    "Task Name": "STEM Exhibition at Sungai Petani",
    "Progress": "Material will be brought by Registrar Office team",
    "Major Issue/Incident": "Short notice, no standard material, need to be collected every time",
    "Action Taken": "Proposed STEM Exhibition Stand and Materials",
    "Report to": "UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "FABE Lecturers, Dean FABE, HOP/s",
    "Category": "Community & Industry Engagement",
    "Status": "In Progress",
    "Progress %": "90.00%",
    "Start Date": "8-Jun-2026",
    "Month Start": "June",
    "Deadline": "18-Jun-2026",
    "Duration (Days)": "10",
    "Day Left Start(Days)": "-24",
    "Day Left (Days)": "-14",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Collect list of exhibition materials and secure transportation with the Registrar's team",
      "Design a modular STEM exhibition stand display that is reusable and compact",
      "Confirm the schedule of lecturers attending the stand as representatives",
      "Draft a feedback form for visitors to gauge outreach effectiveness"
    ]
  },
  {
    "Task Name": "Paperworks for the implementation of VBE and SDE",
    "Progress": "CPD Meeting done, papers presented in UAC",
    "Major Issue/Incident": "Approval and Implementation",
    "Action Taken": "To be presented in Senate",
    "Report to": "UAC, Senate",
    "Strategic Thrust": "Strategy Thrust 1: Academic Excellence and Curriculum Innovation",
    "RASCI": "HOP/s",
    "Category": "Academics & Teaching",
    "Status": "In Progress",
    "Progress %": "75.00%",
    "Start Date": "1-Jun-2026",
    "Month Start": "June",
    "Deadline": "3-Jul-2026",
    "Duration (Days)": "32",
    "Day Left Start(Days)": "-31",
    "Day Left (Days)": "1",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/uac/FMfcgzQgMLxHpWkxdqfvDSfTNXPsgHQh",
    "suggestions": [
      "Consolidate feedback from the UAC presentation and revise the papers",
      "Format the VBE/SDE implementation guidelines to meet Senate template standards",
      "Submit final draft to the Senate secretariat before the agenda lock date",
      "Draft a guide sheet for lecturers to insert VBE/SDE targets into course files"
    ]
  },
  {
    "Task Name": "Sudanese Student Society (SSS) Food Bazar Project",
    "Progress": "SSS request to use FABE's blue boards for their food bazar program",
    "Major Issue/Incident": "Approved but need to monitor implementation",
    "Action Taken": "Ask them to take good care of the boards",
    "Report to": "Record",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "Students",
    "Category": "Community & Industry Engagement",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "12-Jun-2026",
    "Month Start": "June",
    "Deadline": "14-Jun-2026",
    "Duration (Days)": "2",
    "Day Left Start(Days)": "-20",
    "Day Left (Days)": "-18",
    "Milestone": "No",
    "Link to document": "https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzQgMMDrwkVKtXVQCkJwWjmhkpTh",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Migrating Student to Google Domain and Gemini Ultra",
    "Progress": "Unknown",
    "Major Issue/Incident": "Need justification from ICT",
    "Action Taken": "Remind ICT",
    "Report to": "Record, EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "Dean FABE",
    "Category": "Administrative & Faculty Development",
    "Status": "Not Start",
    "Progress %": "",
    "Start Date": "",
    "Month Start": "",
    "Deadline": "10-Jul-2026",
    "Duration (Days)": "46213",
    "Day Left Start(Days)": "",
    "Day Left (Days)": "8",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Draft a detailed business case justification for ICT, highlighting student AI benefits",
      "Schedule a review meeting with the ICT director to address server/domain setup",
      "Prepare email guides and migration instructions for the student body",
      "Run a pilot migration with a small test group (e.g. ARCA leaders) to check configuration"
    ]
  },
  {
    "Task Name": "AI in Built Environment Exhibition March Semester 2026",
    "Progress": "First Exhibition on AI in Built Environment",
    "Major Issue/Incident": "Need to Promote",
    "Action Taken": "Announcement done",
    "Report to": "Record, UAC, EMC",
    "Strategic Thrust": "Strategy Thrust 3: Digital Transformation, Smart Campus and ESG Commitment",
    "RASCI": "FABE Lecturers, Students",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "23-Jul-2026",
    "Month Start": "July",
    "Deadline": "23-Jul-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "21",
    "Day Left (Days)": "21",
    "Milestone": "Yes",
    "Link to document": "https://sites.google.com/view/ai-in-built-environment",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Measured Drawing Presentation IPOH",
    "Progress": "Exhibition Day",
    "Major Issue/Incident": "Opportunity for collobration with Ipoh City Council",
    "Action Taken": "Call for lecturer to consider having exhibition on measured drawing as part of promotion",
    "Report to": "Record, EMC",
    "Strategic Thrust": "Strategy Thrust 7: Enhancing Student Experience",
    "RASCI": "HOP/s, Cluster Leader",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "26-Jun-2026",
    "Month Start": "June",
    "Deadline": "26-Jun-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "-6",
    "Day Left (Days)": "-6",
    "Milestone": "Yes",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Examination Week March 2026",
    "Progress": "Examination",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record",
    "Strategic Thrust": "",
    "RASCI": "KLUST",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "22-Jun-2026",
    "Month Start": "June",
    "Deadline": "26-Jun-2026",
    "Duration (Days)": "4",
    "Day Left Start(Days)": "-10",
    "Day Left (Days)": "-6",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Board of Examination Meeting March 2026",
    "Progress": "BOE Meeting",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "Record",
    "Strategic Thrust": "",
    "RASCI": "Dean FABE, HOP/s, FABE Lecturers",
    "Category": "Academics & Teaching",
    "Status": "Completed",
    "Progress %": "100.00%",
    "Start Date": "3-Jul-2026",
    "Month Start": "July",
    "Deadline": "3-Jul-2026",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "1",
    "Day Left (Days)": "1",
    "Milestone": "Yes",
    "Link to document": "https://docs.google.com/spreadsheets/d/16ksG3vYlMyx6udUKXIpFMKRnaOSNHs3g62RDXYVAUtY/edit?usp=sharing",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "LAM Mock Visit: Internal Audit",
    "Progress": "",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "",
    "RASCI": "",
    "Category": "Academics & Teaching",
    "Status": "",
    "Progress %": "",
    "Start Date": "",
    "Month Start": "",
    "Deadline": "",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "",
    "Day Left (Days)": "",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  },
  {
    "Task Name": "Official LAM Visit: BSAR/MAR Accreditation: Phase 1",
    "Progress": "Planned for visit on Nov or December 2026\nPreparing Documentation to Submit to LAM",
    "Major Issue/Incident": "Student Availability",
    "Action Taken": "Discuss with LAM and Student",
    "Report to": "EMC, UAC, Record",
    "Strategic Thrust": "Strategy Thrust 8: Industrial Engagement and Employability",
    "RASCI": "HOP/s",
    "Category": "Administrative & Faculty Development",
    "Status": "In Progress",
    "Progress %": "5.00%",
    "Start Date": "1-Jul-2026",
    "Month Start": "July",
    "Deadline": "31-Jul-2026",
    "Duration (Days)": "30",
    "Day Left Start(Days)": "-1",
    "Day Left (Days)": "29",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Compile documentation checklist and delegate to cluster leaders",
      "Identify student representatives and check their availability schedule for meetings",
      "Conduct a mock dry-run with internal auditors using the LAM criteria checklist",
      "Establish a dedicated shared drive folder structure for MAR accreditation documentation",
      "Run weekly compilation reviews with HOPs to assess file completion rates"
    ]
  },
  {
    "Task Name": "2027 Scaling Strategy: ASEAN-Wide",
    "Progress": "",
    "Major Issue/Incident": "",
    "Action Taken": "",
    "Report to": "EMC",
    "Strategic Thrust": "",
    "RASCI": "",
    "Category": "Research & Development",
    "Status": "",
    "Progress %": "",
    "Start Date": "",
    "Month Start": "",
    "Deadline": "",
    "Duration (Days)": "0",
    "Day Left Start(Days)": "",
    "Day Left (Days)": "",
    "Milestone": "No",
    "Link to document": "",
    "suggestions": [
      "Review overall goals and document achievements"
    ]
  }
];
